# Generated by Django 5.2.17 on 2026-09-29 10:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, unique=True)),
                ('mood', models.PositiveSmallIntegerField(choices=[(1, 'Sehr schlecht'), (2, 'Eher schlecht'), (3, 'Neutral'), (4, 'Eher gut'), (5, 'Super')])),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
