# Generated by Django 5.2.17 on 2026-09-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_routine_routinecompletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Täglich'), ('weekly', 'Einmal pro Woche')], default='daily', max_length=10),
        ),
    ]
