# Generated by Django 5.2.17 on 2026-09-29 12:10

from django.db import migrations, models


def create_default_focus_labels(apps, schema_editor):
    focus_label = apps.get_model('core', 'FocusLabel')
    for name in (
        'Balance',
        'Fokus',
        'Resilienz',
        'Innere Ruhe',
        'Selbstvertrauen',
        'Zuversicht',
    ):
        focus_label.objects.get_or_create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_routine_frequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='FocusLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='moodentry',
            name='focus_labels',
            field=models.ManyToManyField(blank=True, related_name='mood_entries', to='core.focuslabel'),
        ),
        migrations.RunPython(create_default_focus_labels, migrations.RunPython.noop),
    ]
