# Generated by Django 5.2.17 on 2026-09-29 12:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_focuslabel_moodentry_focus_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='HydrationDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, unique=True)),
                ('goal_ml', models.PositiveIntegerField(default=2000)),
                ('consumed_ml', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
