# Generated by Django 5.2.17 on 2026-09-29 12:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_gratitudeentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, unique=True)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='JournalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('hobbies', models.TextField(blank=True)),
                ('perfect_free_day', models.TextField(blank=True)),
                ('favorite_tea', models.CharField(blank=True, max_length=100)),
                ('favorite_band', models.CharField(blank=True, max_length=100)),
                ('favorite_film', models.CharField(blank=True, max_length=100)),
                ('dream_destination', models.CharField(blank=True, max_length=100)),
                ('want_to_learn', models.TextField(blank=True)),
                ('good_at', models.TextField(blank=True)),
                ('like_about_myself', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
