# Generated by Django 5.2.17 on 2026-09-29 12:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_diaryentry_journalprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diary_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='focuslabel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='focus_labels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gratitudeentry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gratitude_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hydrationday',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hydration_days', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moodentry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mood_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='routine',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='focuslabel',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='gratitudeentry',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='hydrationday',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddConstraint(
            model_name='diaryentry',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_diary_entry_per_user_day'),
        ),
        migrations.AddConstraint(
            model_name='focuslabel',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_focus_label_per_user'),
        ),
        migrations.AddConstraint(
            model_name='gratitudeentry',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_gratitude_entry_per_user_day'),
        ),
        migrations.AddConstraint(
            model_name='hydrationday',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_hydration_day_per_user'),
        ),
        migrations.AddConstraint(
            model_name='moodentry',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_mood_entry_per_user_day'),
        ),
    ]
