# Generated by Django 5.2.17 on 2026-09-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_kitchentableperson_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchentableperson',
            name='avatar',
            field=models.CharField(blank=True, choices=[('😊', '😊'), ('🌸', '🌸'), ('🦋', '🦋'), ('🌼', '🌼'), ('🍵', '🍵'), ('🌙', '🌙'), ('⭐', '⭐'), ('💗', '💗'), ('🍀', '🍀'), ('🐰', '🐰'), ('🦊', '🦊'), ('🐢', '🐢'), ('🐼', '🐼'), ('🐙', '🐙'), ('🦥', '🦥'), ('🌻', '🌻')], default='😊', max_length=8),
        ),
    ]
