# Generated by Django 5.2.17 on 2026-09-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_kitchentableperson_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitchentableperson',
            name='avatar',
        ),
        migrations.AddField(
            model_name='kitchentableperson',
            name='avatar_gender',
            field=models.CharField(choices=[('neutral', 'Neutral'), ('man', 'Mann'), ('woman', 'Frau')], default='neutral', max_length=10),
        ),
        migrations.AddField(
            model_name='kitchentableperson',
            name='avatar_glasses',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kitchentableperson',
            name='avatar_hair_color',
            field=models.CharField(choices=[('#2b2b2b', 'Schwarz'), ('#6b4226', 'Braun'), ('#d9b56a', 'Blond'), ('#a3402b', 'Rot'), ('#b0b0b0', 'Grau'), ('#e6a8c8', 'Pink')], default='#6b4226', max_length=7),
        ),
    ]
