# Generated by Django 5.2.17 on 2026-09-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_kitchentableperson_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchentableperson',
            name='avatar_gender',
            field=models.CharField(blank=True, choices=[('neutral', 'Neutral'), ('man', 'Mann'), ('woman', 'Frau')], default='neutral', max_length=10),
        ),
        migrations.AlterField(
            model_name='kitchentableperson',
            name='avatar_glasses',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='kitchentableperson',
            name='avatar_hair_color',
            field=models.CharField(blank=True, choices=[('#2b2b2b', 'Schwarz'), ('#6b4226', 'Braun'), ('#d9b56a', 'Blond'), ('#a3402b', 'Rot'), ('#b0b0b0', 'Grau'), ('#e6a8c8', 'Pink')], default='#6b4226', max_length=7),
        ),
    ]
