# Generated by Django 5.2.17 on 2026-09-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_kitchentableperson_avatar_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchentableperson',
            name='avatar_background_color',
            field=models.CharField(blank=True, choices=[('#ffffff', 'Weiß'), ('#ffe3ee', 'Rosa'), ('#e3f2ff', 'Blau'), ('#eafbe7', 'Grün'), ('#fff6da', 'Gelb'), ('#f1e6ff', 'Flieder')], default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='kitchentableperson',
            name='avatar_clothing_color',
            field=models.CharField(blank=True, choices=[('#f4c9db', 'Rosa'), ('#bcd8f1', 'Hellblau'), ('#c9e4c5', 'Mintgrün'), ('#f7e1a0', 'Gelb'), ('#d9c2f0', 'Flieder'), ('#f2b7a3', 'Koralle')], default='#f4c9db', max_length=7),
        ),
        migrations.AddField(
            model_name='kitchentableperson',
            name='avatar_hairstyle',
            field=models.CharField(blank=True, choices=[('short', 'Kurz'), ('long', 'Lang'), ('curly', 'Lockig'), ('bun', 'Dutt'), ('bald', 'Glatze')], default='short', max_length=10),
        ),
        migrations.AddField(
            model_name='kitchentableperson',
            name='avatar_skin_color',
            field=models.CharField(blank=True, choices=[('#ffe0c2', 'Hell'), ('#f1c6a0', 'Mittelhell'), ('#d8a373', 'Mittel'), ('#a66a44', 'Mittel-Dunkel'), ('#6b4226', 'Dunkel')], default='#ffe0c2', max_length=7),
        ),
    ]
